### ISSUE TITLE
Orders tab Does not work

### ISSUE THREAD

**Issue by avinashstellar** [namasteashoka/elephant#11]
if i click  on user profile user can't check his order and Notification tab does not work.
Step 1. login with user details
step 2. click on user name and then click on orders and Notifications tab
![issue1](https://user-images.githubusercontent.com/28996484/27760333-a209e902-5e62-11e7-97cb-c60d4d067e27.png)

**Comment by ashoksaha** [comment]
Notifications link not updated.
Notifications page like a message box.
